[package]
name = "rr-tools-lib"
version = "0.1.0"
authors = ["Niakr1s <pavel2188@gmail.com>"]
edition = "2018"

[dependencies]
roxmltree = "^0.4"
log = "^0.4"
pretty_env_logger = "^0.3"
dxf = {git = "https://github.com/IxMilia/dxf-rs.git"}